export const primitives = [
  {
    id: "sql",
    name: "SQL",
    role: "Relational state",
    handle: "sql::<M>(target)",
    methods: "batch · query",
    rule: "A parameterized batch changes one Cell. Queries can require its committed receipt.",
    example: "sql",
    anchor: "sql",
    diagram: ["Typed batch", "SQLite transaction", "Durable receipt"],
  },
  {
    id: "kv",
    name: "KV",
    role: "Scoped atomic metadata",
    handle: "kv::<M>(namespace)",
    methods: "atomic · get · list",
    rule: "Checks and mutations share one shard transaction. Scope determines the partition.",
    example: "basic",
    anchor: "kv",
    diagram: ["Scope + checks", "Atomic mutations", "Versioned values"],
  },
  {
    id: "blob",
    name: "Blob",
    role: "Immutable content",
    handle: "blob::<M>()",
    methods: "mutate · query",
    rule: "Stage parts, then publish their references. Completion makes an attachment visible.",
    example: "blob",
    anchor: "blob",
    diagram: ["Begin + stage parts", "Complete references", "Read at receipt"],
  },
  {
    id: "queue",
    name: "Queue",
    role: "At-least-once work",
    handle: "queue::<M>()",
    methods: "send · claim · ack",
    rule: "Validate a claim lease before external work. Make the work safe to repeat.",
    example: "basic",
    anchor: "queue",
    diagram: ["Send message", "Claim + validate lease", "Work + acknowledge"],
  },
  {
    id: "cron",
    name: "Cron",
    role: "Recurring triggers",
    handle: "cron::<M>()",
    methods: "mutate · get",
    rule: "Bounded maintenance advances due schedules and deduplicates occurrences.",
    example: "schedules",
    anchor: "cron",
    diagram: ["Schedule", "Due maintenance tick", "Durable Effect"],
  },
  {
    id: "workflow",
    name: "Workflow",
    role: "Durable decisions",
    handle: "workflow::<M>()",
    methods: "start · signal · state",
    rule: "Decisions and history survive owner changes. Pin the workflow definition digest.",
    example: "workflow",
    anchor: "workflow",
    diagram: ["Start run", "Recorded decisions", "Durable history"],
  },
  {
    id: "activities",
    name: "Activities",
    role: "Supervised external work",
    handle: "activities::<M>()",
    methods: "ActivitySupervisor",
    rule: "Execute outside SQLite under a validated lease, then record completion in the workflow.",
    example: "workflow",
    anchor: "workflow",
    diagram: ["Activity intent", "Supervisor + lease", "Recorded completion"],
  },
  {
    id: "effects",
    name: "Effects",
    role: "Cross-Cell delivery",
    handle: "effects::<M>(target)",
    methods: "claim · ack",
    rule: "Commit intent in the source Cell. Apply it through an idempotent destination inbox.",
    example: "schedules",
    anchor: "effects",
    diagram: ["Source intent", "Signed delivery", "Destination inbox"],
  },
] as const;
